### ISSUE TITLE
It’s GroundedSAM always for free or not?

### ISSUE THREAD

**Issue by Siwakonrome** [autodistill/autodistill-grounded-sam#12]
It’s GroundedSAM free or not? If not How to get Api key to using this service?

import cv2
import supervision as sv
from autodistill_grounded_sam import GroundedSAM
from autodistill.detection import CaptionOntology

class GroundedSAMOperator:

def init(self, caption):
self.caption = caption
self.base_model = GroundedSAM(ontology=CaptionOntology(self.caption))
self.classes = base_model.ontology.classes()

def call(self, image):
detections = self.base_model.predict(image)
labels = [f"{self.classes[class_id]} {confidence:0.2f}" for _, _, confidence, class_id, _ in detections]
print(labels)
return detections

image = cv2.imread("/content/aluminum.jpg")
caption = { "aluminum workpiece": "aluminum" }
grounded_sam_operator = GroundedSAMOperator(caption)
detections = grounded_sam_operator(image)

mask_annotator = sv.MaskAnnotator()

annotated_frame = mask_annotator.annotate(
scene=image.copy(),
detections=detections)

sv.plot_image(annotated_frame, size=(8, 8))

**Comment by capjamesg** [comment]
Grounded SAM is free to use on your hardware.
