### ISSUE TITLE
Is GroundedSAM setting device?

### ISSUE THREAD

**Issue by EduardoPach** [autodistill/autodistill-grounded-sam#5]
The `GroundedSAM` class doesn't seem to use the DEVICE, which makes me wonder if it gets GPU acceleration. 

see here https://github.com/autodistill/autodistill-grounded-sam/blob/main/autodistill_grounded_sam/grounded_sam.py#L26

**Comment by capjamesg** [comment]
Hello! We also define `DEVICE` in the file in which we load the models and pass it as an argument when loading the models.

See https://github.com/autodistill/autodistill-grounded-sam/blob/main/autodistill_grounded_sam/helpers.py#L72
https://github.com/autodistill/autodistill-grounded-sam/blob/main/autodistill_grounded_sam/helpers.py#L108

**Comment by EduardoPach** [comment]
> Hello! We also define `DEVICE` in the file in which we load the models and pass it as an argument when loading the models.
> 
> 
> 
> See https://github.com/autodistill/autodistill-grounded-sam/blob/main/autodistill_grounded_sam/helpers.py#L72
> 
> https://github.com/autodistill/autodistill-grounded-sam/blob/main/autodistill_grounded_sam/helpers.py#L108

Oh, my bad. I forgot to check the helpers 😅
